apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phpldapadmin
  namespace: services
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - phpldapadmin.acme.test
      secretName: phpldapadmin-tls
  rules:
    - host: phpldapadmin.acme.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: phpldapadmin
                port:
                  number: 80
