apiVersion: v1
kind: Service
metadata:
  name: openldap
  namespace: services
spec:
  type: ClusterIP
  selector:
    app: openldap
  ports:
    - name: ldap
      port: 389
      targetPort: 389
      protocol: TCP
