apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: nad-users
  namespace: dmz
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "nad-users",
      "type": "macvlan",
      "master": "ens18",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "ranges": [
          [
            {
              "subnet": "192.168.1.0/24",
              "rangeStart": "192.168.1.10",
              "rangeEnd": "192.168.1.250",
              "gateway": "192.168.1.1"
            }
          ]
        ]
      }
    }
