apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: itadaki-h2-pvc
  namespace: services
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
