apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: itadaki
  namespace: services
  annotations:
    # Pour réseau local sans accès internet : utiliser selfsigned-issuer
    # cert-manager.io/cluster-issuer: selfsigned-issuer
    cert-manager.io/cluster-issuer: ca-issuer
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - itadaki.acme.test
      secretName: itadaki-tls
  rules:
    - host: itadaki.acme.test
      http:
        paths:
          # /api/* → backend Java
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: itadaki-backend
                port:
                  number: 8080
          # /* → frontend React Router
          - path: /
            pathType: Prefix
            backend:
              service:
                name: itadaki-frontend
                port:
                  number: 3000
