apiVersion: v1
kind: Namespace
metadata:
  name: dmz
  labels:
    zone: dmz
  annotations:
    cilium.io/policy-enforcement: always
---
apiVersion: v1
kind: Namespace
metadata:
  name: services
  labels:
    zone: services
  annotations:
    cilium.io/policy-enforcement: always
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    zone: monitoring
