apiVersion: batch/v1
kind: Job
metadata:
  name: h2-restore
  namespace: services
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: h2-restore
          image: busybox:1.36
          command: ["/bin/sh", "/scripts/restore.sh"]
          volumeMounts:
            - name: h2-data
              mountPath: /data
            - name: backup-storage
              mountPath: /backup
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: h2-data
          persistentVolumeClaim:
            claimName: itadaki-h2-pvc
        - name: backup-storage
          persistentVolumeClaim:
            claimName: backup-pvc
        - name: scripts
          configMap:
            name: backup-scripts
            defaultMode: 0755
